Adds Java 21 and Node.js 20 LTS images
pterodactyl/yolks pull request #48
Opened 2024-01-01 13:42 UTC by oliver194

This pull request adds Java 21 (Eclipse Temurin) and Node.js 20 LTS images

2024-01-01 14:06 UTC, parkervcp requested changes

2024-01-01 14:06 UTC, parkervcp commented on .github/workflows/java.yml
> +          - 21
you should add the `20` here as well

2024-01-01 14:06 UTC, parkervcp commented on .github/workflows/java.yml
> +          - 21
cancel that I see you added nodejs 20 and java 21.

2024-01-01 14:07 UTC, parkervcp approved these changes

2024-01-24 13:57 UTC, KeizerWilmer commented
Is it possible to merge this PR, or are there any pending tasks?

2024-01-24 14:28 UTC, merged